language: c++

os:
  - osx

compiler:
  - clang

before_install:
    - if [ `uname` = "Darwin" ]; then
        ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null;
        brew install castxml;
        git clone https://github.com/gccxml/pygccxml.git;
        cd pygccxml;
        python setup.py install;
        cd ..;
      fi

script:
  - if [ `uname` = "Darwin" ]; then
      make build_documentation;
    fi
