language: c++

os:
  - osx
  - linux

compiler:
  - clang
  - gcc

before_install:
    - if [ `uname` = "Linux" ]; then
         sudo apt-get update;
         sudo apt-get install -y libvorbis-dev libtheora-dev libphysfs-dev libdumb1-dev libflac-dev libpulse-dev libgtk2.0-dev pandoc libcurl4-nss-dev libenet-dev pulseaudio;
         sudo add-apt-repository ppa:allegro/5.2 -y;
         sudo apt-get update -q;
         sudo apt-get install -y liballegro5-dev;
      elif [ `uname` = "Darwin" ]; then
         brew install opusfile libvorbis freetype flac physfs;
         brew install allegro;
      fi

script:
  - make
